### PR TITLE
Show place in queue in browser tab

### PR DESCRIPTION
**Pull request by wylie39**
Show your place in the queue in the browser tab for convenience.

### CODE REVIEW

**Comment by MrGeorgen** [comment]
the queue place is already in the title
https://github.com/themoonisacheese/2bored2wait/blob/f7b827685ff3f8536277a4608cbe580f820090bd/index.html#L22

**Comment by wylie39** [comment]
Really? Just to confirm that the position you are in the queue is in the browser tab name? If so let me know and I will clothes this request.

**Comment by MrGeorgen** [comment]
> Really? Just to confirm that the position you are in the queue is in the browser tab name?

Yes, you probably have many browser tabs open, so you can only see the beginning of the title

**Comment by wylie39** [comment]
Ok, sorry about that.

**Pull request closed without merging**
