### PR TITLE
rewrite in typescript

### PR DESCRIPTION
**Pull request by rob9315**
fixes multiple issues and finishes some previously half-implemented features

### CODE REVIEW

**Comment by rob9315** [comment]
this basically has all the previous functionality, just has to be tested because I don't know if docker works or not.

**Comment by MrGeorgen** [comment]
changes from the last few commits are not included.
you also got something in the .gitignore wrong because you commited the
transpiled js files, but not ts source files

**Comment by rob9315** [comment]
I think I commited both. Though as the js files are built with `npm install` anyways, they should be excluded, right.

**Comment by MrGeorgen** [comment]
>I think I commited both.

Yeah now I see it.

the docker.json and replacing the values is also not required anymore. A env
var for the config can be used (see [doc](https://github.com/lorenwest/node-config/wiki/Command-Line-Overrides)). I already changed the test. The docker container should also use the env var

**Comment by rob9315** [comment]
@MrGeorgen I wanted to ask about the node-config package and why we need it. I don't think using it makes a lot of sense and I consider it to be a lot of bloat. If I cleanly implement the same functionality without the package, is that fine?

**Comment by MrGeorgen** [comment]
> @MrGeorgen I wanted to ask about the node-config package and why we need it. I don't think using it makes a lot of sense and I consider it to be a lot of bloat. If I cleanly implement the same functionality without the package, is that fine?

with node-config we can have a default config and a user config which
overrides options from default config. Otherwise it could be a problem if user
writes his config, update the program to a new version where new config values
must be specified. This could cause a crash.

Also config via an env var I also find every usefull. So we don't need shell
script to replace values in the config for the docker container anymore. Also
other config values when using docker can be set every easily without having
to mount the config file. Additionaly the test script can set the config via
an env var. Before the test script did override the config file, which can be
very painfull if using a very customized config

Also the node-config package is only about 70kb which is not that much and it
only has one dependency. Considering that we have a total of 259 dependencies
I don't find a big deal

**Comment by rob9315** [comment]
Ok I see. Though I still dislike that package, I will work with it.

**Comment by rob9315** [comment]
will be realized differently

**Comment by cristiioan** [comment]
Are there any plans to do the rewirite anymore @rob9315?

**Comment by KozmikNano** [comment]
@cristiioan you can check the progress here: https://github.com/rob9315/2b2wTS/

**Comment by cristiioan** [comment]
I know. He sent me the link.

**Comment by KozmikNano** [comment]
Ok nice, we are still developing it!

**Pull request closed without merging**
