### PR TITLE
Update to discord V.13 (add slash commands)

### LINKED ISSUE #436: Update to discord V.13 (add slash commands)
This is the current project that i will be working on :)

### PR DESCRIPTION
**Pull request by KozmikNano**
Fixes #436

### CODE REVIEW

**Comment by KozmikNano** [comment]
This is still in development
DO NOT PUSH!!

**Review by KozmikNano — COMMENTED** [review]
Fixed that bug for update command

**Comment by KozmikNano** [comment]
I will be adding slash commands later, just wanted to update the discord version just to get started!

**Comment by nickcat325** [comment]
Nice.

**Pull request merged**
