### PR TITLE
Fix npm start (opn -> open)

### PR DESCRIPTION
**Pull request by ZillyHuhn**
Sorry for the previous rushed pr I did not even run ``npm start``. A CI would be nice :)

### CODE REVIEW

**Review by themoonisacheese — APPROVED** [review]

**Comment by themoonisacheese** [comment]
> A CI would be nice :)
what do you mean?

**Comment by ChillerDragon** [comment]
Like a github workflow that runs at least ``npm install`` and maybe there can even be found a way to quickly test if the app launches without crashes.

**Comment by hentai69420** [comment]
pr's have been accepted that don't even run due to missing commas or misspelling

**Comment by themoonisacheese** [comment]
on one hand that's fair, on the other hand i haven't launched minecraft in several years now.
i'd like to let someone else become maintainer and have commit rights, but it's a bit hard for me to trust someone given the countless examples of backdoors.

**Comment by themoonisacheese** [comment]
i realize that i'm not being very clear. the reason i'm not doing implementing a build service is that i have absolutely no fucking idea how to do that.

**Pull request merged**
