### PR TITLE
Particles.JS + flickering undefined fix

### PR DESCRIPTION
**Pull request by KohimaNayagato**

### CODE REVIEW

**Comment by wylie39** [comment]
It would be great If you could add a pull request message so we know what you changed and why you changed it.

Thanks, 
A developer who doesn’t like empty commit messages.

**Comment by KohimaNayagato** [comment]
I'd say the title is quite self explanatory but I'll sum it up to you. Slight issue that was annoying me was the flickering "undefined" text when you were in queue so I fixed that, added a particles.js background to the webserver and added center tags (I'll probs do another commit to remove the center tags and add them to the CSS later) to make the webserver look less messy/bland.

-KohimaNayagato

**Comment by MrGeorgen** [comment]
I can only barely see the particles and you should use particels.js as npm package. You fixed the flickering, but I'd if to see "None" instead of "undefined"

**Comment by themoonisacheese** [comment]
that is a good addition, however 2b2w is distributed as a GNU GPL 3.0 program, and particle.js is distributed as an MIT License program. merging this request in its current implies either one of these licenses changing for the other one and i'd rather just have particle.js distributed through NPM, circumventing that problem and possible security problems by always having an up to date version.

apart from that, i'd merge this as i see no issue with it.

**Comment by KohimaNayagato** [comment]
I'll move it to NPM and try to refine it a little bit more and make another merge request. 

-KohimaNayagato

**Comment by KohimaNayagato** [comment]
Re-opened merge req, imports particles.js from NPM now, fixed flickering undefined while not in queue and thats pretty much it 😄

**Comment by wylie39** [comment]
Looks good, can we wait on merging until I finish the test script and github action. It should be done tonight.

**Comment by KohimaNayagato** [comment]
Sounds good to me 👍

**Comment by themoonisacheese** [comment]
i see no changes to package.json, which means particle.js won't be tagged as a dependency when running npm install.

**Comment by KohimaNayagato** [comment]
Oh crap, I added it to mine but I must have not committed it, let me fix it 1s

**Comment by KohimaNayagato** [comment]
It is committed, you must've missed it.

**Review by themoonisacheese — APPROVED** [review]

**Comment by themoonisacheese** [comment]
you're absolutely right, i got confused by the fact that the previous line also changed for the added comma.

**Pull request merged**
