### PR TITLE
Put code in folder structure

### PR DESCRIPTION
**Pull request by wylie39**
These commits move all code into folders, this makes the top-level less cluttered.
Includes updated readme and tests.

### CODE REVIEW

**Comment by wylie39** [comment]
That took too many attempts to set the working directory.

**Comment by themoonisacheese** [comment]
surely not moving package.json to be able to call npm start/install from the root directory allows for better usability?

**Comment by wylie39** [comment]
Good call, I will move the package.json and config files to the root.

**Comment by wylie39** [comment]
This is going to take more work than I thought, I will reopen when I have it finished,

**Comment by themoonisacheese** [comment]
npm should have mechanisms to change the current working directory (or just have the start script call cd src/), just FYI

**Pull request closed without merging**
