### PR TITLE
Added custom server icons and preventing Cloudflare bans in edge cases

### PR DESCRIPTION
**Pull request by czho**
also checked for invalid account

### CODE REVIEW

**Comment by czho** [comment]
There's an error I didnt realize, dont merge yet.

**Review by AstroOrbis — APPROVED** [review]

**Comment by AverageComet250** [comment]
Is this working yet?

**Comment by MrGeorgen** [comment]
> Is this working yet?

no the test failed

**Comment by AverageComet250** [comment]
I meant is @czho still working on this? I don't see any commits since 13 days ago.

**Comment by czho** [comment]
tests and everything work now

**Comment by AverageComet250** [comment]
Just to confirm, It grabs the icon from the server it connects to, right?

**Comment by MrGeorgen** [comment]
It should read the image from a png file, as encoding to base64 is not easy to
do for some people.

see also #223

>Just to confirm, It grabs the icon from the server it connects to, right?

no, you put your image in the favicon.json

**Comment by MrGeorgen** [comment]
also the programm should not be closed because of invalid credentails because
if log in to often you get banned from the auth servers for 30 min and it says
your credentails are wrong. This happened a lot during development but less
since the token is stored

**Comment by czho** [comment]
ill update this with the changes you requested and the new commits added soon.

**Comment by czho** [comment]
even though theres not that much here, im really busy, ill close this untill i have time to get it to merge

**Pull request closed without merging**
