### PR TITLE
Add '(' to fix link in README.md

### PR DESCRIPTION
**Pull request by shivamCode0**
The formatting of the link to open issues is broken. I added a `(` character to fix it.

### CODE REVIEW

**Comment by qualk** [comment]
I did that and many more README.md improvements.

**Comment by shivamCode0** [comment]
Sorry, I saw that but I was thinking that maybe it would also be easier to do this small change first at least. I don't think yours is bad or anything.

**Comment by qualk** [comment]
I had to close mine because my other commits were also transferred to my PR.

**Comment by MrGeorgen** [comment]
I'm closing this because the same fix in #360

**Pull request closed without merging**
