### PR TITLE
New web app

### PR DESCRIPTION
**Pull request by nothotscott**
I added some much needed refactoring to the web server

- Removed old vanilla web pages in favor of react and react-bootstrap
- Modified the web server to run the transpiled web app (via webpack)
- Should now be highly extensible to add new APIs (like starting at a specific time or calculating the best time to play) which hopefully I can add soon

I may also add https support for those who would like to port-forward or open the web interface to the broader internet
chrome_qQj9w0KnRm

### CODE REVIEW

**Comment by KozmikNano** [comment]
I see only one major problem on this right now. It most likely can’t compile binaries right of the box without issues.

**Comment by nothotscott** [comment]
> I see only one major problem on this right now. It most likely can’t compile binaries right of the box without issues.

This should be fixed now. Running `npm run build` (aka `webpack`) is now a prerequisite to `node build.js`. Issues caused by nexe's virtual filesystem when serving web pages should also be fixed.

**Comment by rob9315** [comment]
Any specific reason the react javascript files are named .js and not .jsx?

**Comment by nothotscott** [comment]
> Any specific reason the react javascript files are named .js and not .jsx?

Not particularly. I've never used the jsx extension in a react project before. Though since this now mixes jsx and ES6, it wouldn't be a bad idea. Still, all react source should be in (and stay in) the `web-src` directory

**Comment by qualk** [comment]
I kinda like the past design

**Comment by cristiioan** [comment]
This one is better but I think mostly anyoane wan't a better discord bot.

**Comment by KozmikNano** [comment]
Could you bring back the old background? Also I don’t think we need the discord bot. Also please have a look at the conflicting things just in case.

**Comment by HackerDaGreat57** [comment]
This is needed. The localhost web page sucks up CPU, GPU and a little bit of RAM by displaying that fancy JS graphic in the background. It gets boring after a while too.

**Comment by KozmikNano** [comment]
> This is needed. The localhost web page sucks up CPU, GPU and a little bit of RAM by displaying that fancy JS graphic in the background. It gets boring after a while too.

I can add a config option to remove that if you would like :)

**Comment by HackerDaGreat57** [comment]
> > This is needed. The localhost web page sucks up CPU, GPU and a little bit of RAM by displaying that fancy JS graphic in the background. It gets boring after a while too.
> 
> I can add a config option to remove that if you would like :)

Yes please 😊

**Comment by cristiioan** [comment]
I think that better we should remove completely the webpage and only keep a small discord bot

**Comment by HackerDaGreat57** [comment]
There's no point of removing something that takes up barely any resources (the new web page in this PR) that barely takes up ~50KB. I respectfully disagree that only a discord bot should be kept.

**Comment by cristiioan** [comment]
> There's no point of removing something that takes up barely any resources (the new web page in this PR) that barely takes up ~50KB. I respectfully disagree that only a discord bot should be kept.

@HackerDaGreat57 whiule it only take such a small amount, you have to code 2 times more to keep both a webapp and discord bot uptodate

**Comment by themoonisacheese** [comment]
The webpage stays for as long as it is functional. Just because you personally don't use it and only use the discord doesn't mean everyone does. As a matter of fact, the webpage was originally the only means of accessing the proxy since everyone on earth has a browser but people may not have a discord account/ may be banned from discord/ may not have a verified email, which is required to create bot accounts.

if anything, the discord bot is the system that is most likely to go (even if there are currently no plans to remove it), since discord.js is considerably larger than this entire repo, is harder to use, and requires regular updating to keep up with discord API changes. meanwhile, the webpage is using a global standard in one of the simplest ways possible and is thus unlikely to require changes in the foreseeable future, bar this PR which aims to make it prettier without changing the function.

removing the web app is completely out of the question for as long as the discord bot is in this codebase.

**Comment by KozmikNano** [comment]
So, @themoonisacheese are we going to close the pr or merge it?

**Comment by themoonisacheese** [comment]
> So, @themoonisacheese are we going to close the pr or merge it?

@nothotscott is this ready to merge? I.e. is it at least as functional as the thing it's replacing?

**Comment by KozmikNano** [comment]
I will test it today and see

**Comment by KozmikNano** [comment]
@nothotscott It is currently broken right now. I fixed the install to allow the web server to be built but there is still some problems.

**Comment by nothotscott** [comment]
> @nothotscott It is currently broken right now. I fixed the install to allow the web server to be built but there is still some problems.

Thanks. I did a clean build on my machine and it worked fine.

**Comment by KozmikNano** [comment]
Pls fix the checks, there needs to be a check mark next to your pull request

**Comment by themoonisacheese** [comment]
closing as abandonned.

**Pull request closed without merging**
