### PR TITLE
Major update to the Readme!

### PR DESCRIPTION
**Pull request by KozmikNano**
This new readme file just ads more look and feel to the project!

### CODE REVIEW

**Comment by rob9315** [comment]
I think that looks good, though might be a little over the top with the styling in the beginning. Let's see what @themoonisacheese thinks about this

**Comment by KozmikNano** [comment]
Ok cool. Glad you like this!

**Review by themoonisacheese — CHANGES_REQUESTED** [review]
A few things:
It looks like the shields at the beginning are broken, or maybe it's just my 
internet?

the install instructions for non windows platforms are technically correct, although we do release Linux and Mac binaries as well. The installation instructions for every platform should be akin to "download and execute the binary appropriate for your platform".

In general, I don't think it is necessary to install node anymore since it should be packaged inside the binaries. It may be worth it to test if that's indeed the case. 

I think it would be most efficient to nuke most things about docker in the readme and simply leave the precomposed part, and people who want to dive in can do so at their leisure. Also, since the "how to use" section has been nuked, it it's probably efficient to just not reference it at all in the new readme.

"View demo" and "read the docs" links can go as we have neither of these things

These are not failings on your part, just things that happen to need changing while the readme is being updated.

**Comment by KozmikNano** [comment]
I had the separate install section for those because the pre-compiled binaries for those platform don’t work as intended(They don’t install or run as scripts). I can remove all the parts as listed but I am still confused on what parts of the docker section you would like me to remove. Am I only including the docker precomposed section and nothing else?

**Comment by themoonisacheese** [comment]
i'm unsure what you mean by "don't install or run as scripts"? As far as i'm aware, the binaries are (should be at least) standalone for every platform.

yes, everything about docker except for the precomposed part (which i've been told is usually just referred to as "using docker") can go.

what i was saying about that is that there is no longer a comprehensive "how to use" section where one could refer to after downloading the programs. steps 3 and up from the docker self compose section are the only remnants and not only can they be easily overlooked, i'm asking you to remove that section entirely so moving those usage steps to their own section would make the most sense (only steps 3 onwards, the first 2 are docker-specific)

**Comment by KozmikNano** [comment]
Ok, so you know how on windows you run ".exe" files. Well on Linux it is ".sh", ".deb" or ".appimage". Mac, I am unfamiliar with so I have no idea its file extension is. The binary for the nonwindows platforms doesn't have a file extension. This causes many problems for the platforms that run then. Because of that, I left the old install way there.

**Comment by KozmikNano** [comment]
I have removed the stuff you wanted me to except for the Linux and mac section because of the problem I told you about above. I also added back that how-to section because I realized that it was important. Adding to that I added a line that told them to look at the commands section if they didn't want to use the web interface.

**Comment by rob9315** [comment]
please take a look at [this](https://github.com/KozmikNano/2bored2wait/pull/1)

**Comment by KozmikNano** [comment]
@themoonisacheese The edits has been made and hopefully been met to the needs.

**Comment by rob9315** [comment]
Can you please adjust the donation button to be in the same style as the others? I don't really know how to do that, but it would fit in better

**Comment by KozmikNano** [comment]
I will try to do that.

**Comment by KozmikNano** [comment]
@rob9315 The new look is here!

**Comment by KozmikNano** [comment]
@themoonisacheese and @rob9315 is there a discord I can contact you guys at GitHub. is a little slower for trying to contact others.

**Comment by rob9315** [comment]
This seems ready for merge.
@KozmikNano I added a discord server to my readme

**Comment by KozmikNano** [comment]
Ok thanks.

**Pull request merged**
