### PR TITLE
chunk saving and other stuff

### PR DESCRIPTION
**Pull request by sijanec**

### CODE REVIEW

**Comment by themoonisacheese** [comment]
after testing, it doesn't look like this is working at all.
the webpage doesn't open, the default port has been changed to an https port despite the webserver still using http, and pressing "start queuing doesn't do anything.
when you fix that, i'll be able to test if it actually works (after waiting 12h for queue smh)

**Comment by sijanec** [comment]
will check, maybe I forgot to commit. I'm using a nginx proxy for HTTPS and
I forgot to change that.

**Comment by SiebeDW** [comment]
This is just a quick fix that isnt good. You should listen for block updates, chunk unloading etc

**Comment by sijanec** [comment]
Yes, I agree, but spamming that many packets at once would not be a great
idea. This is indeed a quick fix for saving just enough chunks to allow the
player to leave the area and get fresh chunks.

V V čet., 7. maj 2020 ob 11:42 je oseba SiebeDW <notifications@github.com>
napisala:

**Comment by SiebeDW** [comment]
Sorry for late reply, didnt really mean that. What i meant is keeping track of the updates and directly modifying it to the chunk cache. So sending the chunks will include changes

**Comment by MrGeorgen** [comment]
I'll this because all things are already implemented

**Pull request closed without merging**
